### PR TITLE
Introduce exception raygun_custom_data instance method

### PR DESCRIPTION
**Pull request by TSMMark**
To support the case:

I want to raise an exception and have my Rack middleware(s) handle it. However, I also want to include custom data to raygun.

AFAICT this case was not supported, so here we are. Open to feedback. Thanks!

### CODE REVIEW

**Comment by fundead** [comment]
Thanks for your contribution! This is a good use case to support and lines up with features available in other language providers e.g Raygun4JS, so we'll definitely be including this in some form. There's a couple of additional considerations to handle other scenarios including the ability to accept a Proc etc, but I'll be getting one of the team to review this further next week for you. We'll be in touch again shortly.

**Comment by UberMouse** [comment]
Pretty happy with this as is so I'm merging it. I'll be adding a proc to allow a global hook for custom data as per #28 as well.

**Comment by TSMMark** [comment]
@UberMouse Awesome! Any idea how long til a gem release includes this?

**Comment by UberMouse** [comment]
I'll release v1.3 most likely sometime on Monday (GMT+13)

**Comment by UberMouse** [comment]
Hey @TSMMark, we've opted to delay the feature I was waiting on for the Monday release (PR #107) so I've just released 1.3 now. Let me know if you find any issues :)

**Pull request merged**
