### PR TITLE
Typo fix, and standardizing header spacing

### PR DESCRIPTION
**Pull request by fourseven**
There was a typo in one of the titles, and both spellings of 'customize'. Have also added in spaces before the markdown header definitions, which makes the readme easier to read (when editing).

### CODE REVIEW

**Comment by jamiepenney** [comment]
:+1: Thanks!

**Comment by nikz** [comment]
@fourseven customise is the UK spelling :P But yeah, better to have the US version given "initialize"

No idea how I fat fingered "Parameter" that badly however, thanks.

**Comment by fourseven** [comment]
yes, but both were present (customize and customise) @nikz - so I figured that the US version was more appropriate for OSS.

**Comment by nikz** [comment]
@fourseven yeah, OS X autocorrect strikes again :camel:

**Comment by fourseven** [comment]
Always a bad time, I think it's the first thing I turn off on new Macs :smirk_cat:

**Pull request merged**
