### PR TITLE
Feature/sidekiq affected user

### PR DESCRIPTION
**Pull request by ushmakapure**
Opening a PR to add some functionality specifically for Sidekiq workers. We, at Later, have a lot of our functionality in Sidekiq workers and have found it useful to track what users are being affected. We've been using similar middleware since April and it's been working well. 

Could you please confirm that a user object is required for tracking affected users? Would it be possible to use a hash or something else at all? 

Please do let me know of any feedback you may have.

Thanks, 
Ushma

### CODE REVIEW

**Comment by UberMouse** [comment]
Hi Ushma,

Thanks for this, definitely a useful feature. I've had a quick look and it looks ok but I'll get back to you tomorrow after I've had a chance to think about it more thoroughly. 

Thanks,
Taylor

**Comment by ushmakapure** [comment]
Hi Taylor, 
Thanks for getting back to me. I know it's the weekend for you now, but I'd love to hear any feedback you have on Monday. 

- Ushma

**Comment by UberMouse** [comment]
Sorry for the delay in getting back to you Ushma, was busy with other work tasks. I've now tested this and made a few small changes and I'll be merging it in now. Thanks again for this :)

**Comment by ushmakapure** [comment]
Thanks Taylor :) Glad to be able to contribute.

**Pull request merged**
